### ISSUE TITLE
Just a code suggestion

### ISSUE THREAD

**Issue by ArjixWasTaken** [0xSTAR/NH-DL#1]
Don't use a try catch to verify if anything is an int.
Just convert them to a string and then use [string.isdigit()](https://docs.python.org/3/library/stdtypes.html#str.isdigit)

`"1".isdigit()` -> `True`
`"1.0".isdigit()` -> `False`
`"a".isdigit()` -> `False`

This is about the method [`isInt`](https://github.com/0xSTAR/NH-DL/blob/main/src/__main__.py#L99-L105) which could be rewritten as
```python
def isInt(x) -> bool:
    return str(x).isdigit()
```

I am not here to nag at you, I just want to show you that there are a lot of great built-in methods in python that you can utilize to make your life easier.

**Comment by 0xSTAR** [comment]
Thank you for the suggestion. I must've missed that when I was reading the Python documentation or never got around to using that built-in method for strings. 
I've addressed it now, so yeah.
I appreciate that you took the time to look at what I wrote and gave feedback.

**Comment by ArjixWasTaken** [comment]
Np mate
