### ISSUE TITLE
Downloads don't wanna work.

### ISSUE THREAD

**Issue by nanashi89** [0xSTAR/NH-DL#2]
I boot up the latest version of NH-DL and enter the six-digit number. It creates a new folder but doesn't DL anything...

**Comment by 0xSTAR** [comment]
Fixed. Fixed. Fixed!

I did a real CloudFlare bypass now this morning. I feel very happy right now and I hope you will be happy too. 
Version 1.1.1, a patch, is coming, be ready, it will have the downloads up and working again.

Cheers friend!
